nao_main_homepage:
    path:     /
    defaults: { _controller: NAOMainBundle:Main:home }

nao_main_observation:
    path: /observation
    defaults: {_controller: NAOMainBundle:Main:observation }

nao_main_admin:
    path: /admin
    defaults: {_controller: NAOMainBundle:Main:admin}
