<?php

namespace AppBundle\Repository;

/**
 * BirdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BirdRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllByNameAsc()
    {
        $qb = $this->createQueryBuilder('b');
        $qb->orderBy('b.name','ASC');
        return $qb->getQuery()->getResult();
    }

    public function searchBirds($plumage = NULL,  $couleur_bec = NULL, $pattes = NULL, $forme_bec = NULL)
    {
        $qb = $this->createQueryBuilder('b');

        if ($plumage) {
            $qb->andWhere("b.plumage = :plumage")->setParameter("plumage", $plumage);
        };
        if ($couleur_bec) {
            $qb->andWhere("b.couleur_bec = :couleur_bec")->setParameter('couleur_bec', $couleur_bec);
        };
        if($pattes) {
            $qb->andWhere("b.pattes = :pattes")->setParameter('pattes', $pattes);
        };
        if($forme_bec) {
            $qb->andWhere("b.forme_bec = :forme_bec")->setParameter('forme_bec', $forme_bec);
        };
        $qb->orderBy('b.name','ASC');

        return $qb->getQuery()->getResult();
    }

    public function findAllByNameAscWithLastObservation()
    {
        $qb = $this->createQueryBuilder('b');
        $qb->orderBy('b.name','ASC')
            ->leftJoin('b.observations', 'o')
            ->andwhere('o.isValidated = :isValidated')
            ->setParameter('isValidated', true)
            ->orderBy('o.observedAt', 'DESC');
        return $qb->getQuery()->getResult();
    }
}
