<?php

namespace AppBundle\Repository;

/**
 * BirdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BirdRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllByNameAsc()
    {
        $qb = $this->createQueryBuilder('b');
        $qb->orderBy('b.name','ASC');
        return $qb->getQuery()->getResult();
    }
}
