<?php

namespace AppBundle\Repository;

/**
 * TaxrefRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxrefRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllByNameAsc()
    {
        $qb = $this->createQueryBuilder('t');
        $qb->orderBy('t.nomScientifique','ASC');
        return $qb->getQuery()->getResult();
    }
}
