<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllByNameASCExceptAdmin() {
            $qb = $this->createQueryBuilder('u');
            $qb->where('u.username != :username')
                ->orderBy('u.username','ASC')
                ->setParameter("username", 'admin');
            return $qb->getQuery()->getResult();
    }

}
