<?php

namespace AppBundle\Repository;

/**
 * WebserviceUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebserviceUserRepository extends \Doctrine\ORM\EntityRepository
{
}
