# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    providers:
        main_provider:
            entity:
                class: NAOMainbundle:User
                property: username

    encoders:
        NAO\MainBundle\Entity\User:
            algorithm: bcrypt

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            http_basic: ~
            provider: main_provider

    access_control:
        - {path: ^/admin, roles: ROLE_ADMIN}
