# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
            mainProvider:
                entity:
                    class: NAO\UserBundle\Entity\User
                    property: username
    encoders:
            Symfony\Component\Security\Core\User\User: plaintext
            NAO\USERBUndle\Entity\User: plaintext

    role_hierarchy:
        ROLE_ADMIN: [ROLE_NATURALISTE, ROLE_USER]
        ROLE_NATURALISTE: [ROLE_USER]

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        mainFireWall:
            pattern: ^/
            anonymous: true
            provider: mainProvider
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path: logout
                target: login
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
